### ISSUE TITLE
Не обновляет данные

### ISSUE THREAD

**Issue by urtaevS** [egmen/moscow_transport#1]
Версия приложения 24.1.1.
Данные показывает за предыдущий день.

**Comment by urtaevS** [comment]
Установка через HACS в HAos. (Если я правильно понимаю вопрос)

Данные из интеграции:
![Screenshot_2024-05-21-12-41-33-30_c3a231c25ed346e59462e84656a70e50.jpg](https://github.com/egmen/moscow_transport/assets/66906118/1e647771-397c-401d-8bf4-b0d4fc7713dd)

Данные из приложения "Московский транспорт":
![Screenshot_2024-05-21-12-42-08-98_3197c277add0701a52b03843bc34ec6e.jpg](https://github.com/egmen/moscow_transport/assets/66906118/d5638b4a-9831-495e-ad2f-25f17bfe3141)

**Comment by egmen** [comment]
Еще как вариант поискать другие сенсоры с moscow_transport в названии. Плагин генерирует название сенсора по названию настройки name:
```yaml
    name: К метро
```
Видимо, это имя как раз при первоначальной настройке из примера привязалось к сенсору. А Ваш сенсор называется по-другому.

**Comment by urtaevS** [comment]
guid остановки
bf1f933d-d184-43fe-ad2a-83ebf77c90df

Более никаких сенсоров нет.
![Screenshot_2024-05-21-17-02-12-06_c3a231c25ed346e59462e84656a70e50.jpg](https://github.com/egmen/moscow_transport/assets/66906118/7a2938b0-6ec7-44dc-9b2c-fb2dc33257d5)

Мой конфиг:
`- platform: moscow_transport
  name: -> Метро
  stop_id: bf1f933d-d184-43fe-ad2a-83ebf77c90df
  routes:
    - 737
    - 108
    - 94
`

**Comment by urtaevS** [comment]
Удалил сенсор.
Описал по умолчанию

sensor:
  - platform: moscow_transport
    stop_id: 4a2cb004-b0b9-4306-a2ff-92c5b9327bd1

Стал обновлятся😁
